timezone: Etc/UTC
source: site
paths:
  uploads: images
  static: ''
collections_config:
  data:
    path: _data
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: collections/_posts
    url: /blog/[full_slug]/
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/post.md
  es_posts:
    path: collections/_es-posts
    url: /es/blog/[full_slug]/
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/post.md
  pages:
    path: collections/_pages
    url: /[full_slug]/
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.md
  es_pages:
    path: collections/_es-pages
    url: /es/[full_slug]/
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.md
  projects:
    path: collections/_projects
    url: /project/[full_slug]/
    description: ''
    icon: work_outline
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
  es_projects:
    path: collections/_es-projects
    url: /es/project/[full_slug]/
    description: ''
    icon: work_outline
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
  testimonials:
    path: collections/_testimonials
    disable_url: true
    icon: format_quote
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    preview:
      subtext:
        - key: position
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/testimonial.md
  es_testimonials:
    path: collections/_es-testimonials
    disable_url: true
    icon: format_quote
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    preview:
      subtext:
        - key: position
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/testimonial.md
  drafts:
    path: collections/_drafts
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  es_drafts:
    path: collections/_es-drafts
    create:
      publish_to: es_posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading: English
    collections:
      - pages
      - projects
      - testimonials
      - posts
      - drafts
  - heading: Spanish
    collections:
      - es_pages
      - es_projects
      - es_testimonials
      - es_posts
      - es_drafts
  - heading: Settings
    collections:
      - data
_inputs:
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true