title: Vonge

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../component-library

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /project/:name
  testimonials:
    output: false
  posts:
    output: true
    permalink: /blog/:name
  es-pages:
    output: true
    permalink: /es/:name
  es-projects:
    output: true
    permalink: /es/project/:name
  es-testimonials:
    output: false
  es-posts:
    output: true
    permalink: /es/blog/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.md
    values:
      permalink: /
  - scope:
      type: es-pages
      path: _es-pages/index.md
    values:
      permalink: /es/
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: es-projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: es-posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
